### ISSUE TITLE
Name resolution error on master

### ISSUE THREAD

**Issue by uasi** [jeaye/ncurses-rs#91]
```toml
# Cargo.toml
# ...
[dependencies.ncurses]
git = "https://github.com/jeaye/ncurses-rs"
rev = "master"  # == 1c09de2ceac3bf98981e0093938eba34dacf4f2f
default-features = false  # Disable "wide" to build on OS X
```

```rust
// src/main.rs
extern crate ncurses;
fn main() {
    ncurses::initscr();
    ncurses::endwin();
}
```

---

```
% cargo build
   Compiling ncurses-test v0.1.0 (file:///Users/uasi/ncurses-test)
src/main.rs:3:5: 3:21 error: unresolved name `ncurses::initscr`
src/main.rs:3     ncurses::initscr();
                  ^~~~~~~~~~~~~~~~
src/main.rs:4:5: 4:20 error: unresolved name `ncurses::endwin`
src/main.rs:4     ncurses::endwin();
                  ^~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
Could not compile `rust-ncurses-color`.

To learn more, run the command again with --verbose.
```

```
% rustc --version --verbose
rustc 1.1.0 (35ceea399 2015-06-19)
binary: rustc
commit-hash: 35ceea3997c79a3b7562e89b462ab76af5b86b22
commit-date: 2015-06-19
host: x86_64-apple-darwin
release: 1.1.0
```
